### ISSUE TITLE
Residue files Console and Python-Fu

### ISSUE THREAD

**Issue by Gfurst** [khalim19/gimp-plugin-export-layers#30] opened 2016-01-07 17:02 UTC
Don't if its specific to this plugin, but whenever I open a file with gimp, it creates two empty files, called Console and Python-Fu.
I know these are related with the scripting within gimp, but found nothing of others with this issue.
This behavior started after installing the plugin.

My system is Debian Jessie, and GIMP 2.8.14

**Comment by khalim19** [comment] 2016-02-28 17:25
That is strange indeed. Where are the files created?

**Comment by Gfurst** [comment] 2016-02-29 03:43
they're created on whatever folder gimps opens with, eg opening a random file, they will be created into the same folder,
however I was using the gimp version of the debian stable, since then I've moved to arch with a recent gimp version,
can't reproduce the issue anymore, so I think you can close the issue due to old gimp version,

**Comment by khalim19** [comment] 2016-02-29 08:29
I can't reproduce it either, I'll close this issue.

**Closed by khalim19** 2016-02-29 08:29 UTC
