### ISSUE TITLE
After install no new menu 'export to layer'

### ISSUE THREAD

**Issue by ecodiv** [khalim19/gimp-plugin-export-layers#31] opened 2016-02-02 08:36 UTC
See below when starting up from the command line, I get the following:

```
paulo@paulo-HPZ600:~$ gimp
This is a development version of GIMP.  Debug messages may appear here.

(/home/paulo/.config/GIMP/2.9/plug-ins/export_layers.py:8937): LibGimpBase-ERROR **: gimp_wire_write_msg: the wire protocol has not been initialized

(gimp-2.9:8926): LibGimpBase-WARNING **: gimp-2.9: gimp_wire_read(): error
 mapped '<Toolbox>/Xtns/Misc' to '<Image>/File/Create/Misc'
 mapped '<Toolbox>/Xtns/Photo' to '<Image>/Filters/Extensions/Photo'
gimp_display_shell_profile_update
gimp_display_shell_profile_update
```

**Comment by khalim19** [comment] 2016-02-28 17:26
It seems from the output that you're using GIMP 2.9, which is a development version. Can you reproduce this in 2.8?

**Comment by ecodiv** [comment] 2016-03-04 08:22
True, I am using 2.9. I haven't installed 2.8, but when finding time I 
will install and test

**Comment by GimmickyApps** [comment] 2016-03-25 07:40
I'm getting this on 2.8.16:

```
C:\Program Files\GIMP 2\bin>gimp-console-2.8.exe
GIMP-Warning: Bad interpreter referenced in interpreter file C:\Program Files\GI
MP 2\lib\gimp\2.0\interpreters\pygimp.interp: /win32dev/_newdev/deps/gimp/python
\pythonw.exe

GIMP-Warning: Bad interpreter referenced in interpreter file C:\Program Files\GI
MP 2\lib\gimp\2.0\interpreters\pygimp.interp: /win32dev/_newdev/deps/gimp/python
\pythonw.exe

GIMP-Error: Unable to run plug-in "export_layers.py"
(C:\Users\Gimmicky\.gimp-2.8\plug-ins\export_layers.py)

Failed to execute child process (No such file or directory)

GIMP-Error: Unable to run plug-in "export_layers"
(C:\Users\Gimmicky\.gimp-2.8\plug-ins\export_layers)

Failed to execute child process (No such file or directory)
```

I have no other plugins installed, but I did successfully install an extension before.  I put it, well, where it says it's finding it...

**Comment by khalim19** [comment] 2016-03-25 09:50
@GimmickyApps Looks like the `C:\Program Files\GIMP 2\lib\gimp\2.0\interpreters\pygimp.interp` file points to an invalid Python installation. Open up the file and try changing

    /win32dev/_newdev/deps/gimp/python\pythonw.exe

to

    C:\Program Files\GIMP 2\Python\pythonw.exe

**Comment by GimmickyApps** [comment] 2016-03-25 15:29
D'oh!  OK, I tried that and it didn't work, and I soon realized that's because that file doesn't exist either, and then it dawned on me that this was probably an installation-time option that I would have unchecked, since I haven't needed plugins before, just something a little fancier than Paint i.e. with layers and transparency support!  Indeed, it is.  I bet it will work now...

**Comment by GimmickyApps** [comment] 2016-03-25 15:32
Yep, and I got a callback that the installer would have replaced the file you mentioned the way you mentioned, too.

Not only that, the plugin shows up, and I just tried an export, it works perfectly.  Thanks for sharing this!

**Comment by khalim19** [comment] 2016-03-25 20:47
Great to hear that. I'll clarify the installation instructions a bit.

**Comment by cbjohnso** [comment] 2016-05-05 17:32
Hello World! Very inexperienced Windows user here having trouble installing the plugin into GIMP. 

I have GIMP 2.8.16 installed. I installed python afterward. When I go to Filters>Python-Fu>Console it brings up the following:

GIMP 2.8.16 Python Console
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)]
>>> 

This should be a workable version, correct?

I have copied the export_layers folder and export_layers.py file to the following directory:

C:\Program Files\GIMP 2\lib\gimp\2.0\plug-ins

Despite this, after re-initializing GIMP (even after a system reboot), I do not see the Export Layers option under the File menu.

Furthermore I cannot find the plugin using the Help>Plug-In Browser tool.

I am at the end of my limits for troubleshooting (again, not a coder, limited computer literacy here, so bear with me).

Any help would be greatly appreciated. Thanks!

**Comment by IBwWG** [comment] 2016-05-05 18:14
@cbjohnso I think you've got the wrong install dir for the plugin.  You want the one in your users dir.  On Windows 7 it's something like C:\Users\Gimmicky\.gimp-2.8\plug-ins\ but for your version of Windows it may differ a bit.

**Comment by cbjohnso** [comment] 2016-05-05 18:35
@IBwWG Thank you so much! I thought it was something simple like the wrong directory. Perhaps I missed something in the installation documentation or maybe it could be clarified for us handicapped by Windows (and ignorance).. Again, many thanks for your insight!

**Comment by IBwWG** [comment] 2016-05-05 18:37
No prob, glad to have helped :)

**Comment by khalim19** [comment] 2016-05-05 18:56
Thanks IBwWG for the assistance.

I clarified the bit about the installation folder, quite a few people have been installing it in the system path for some reason (even though _that_ should work as well...).

**Comment by Mavikaya8** [comment] 2017-09-21 14:13
Hi there! 

I am experiencing the same kind of problem as cbjohnso. I am also illiterate in programming.

I have:  64bit Windows 10 , Python 2.7.22 and Gimp 2.8

I uninstalled Gimp. Then installed Python, then reinstalled Gimp.
In console I get this:
![image](https://user-images.githubusercontent.com/32169391/30700225-fecd49f8-9eb4-11e7-90bf-88cd2842842e.png)

I put the layer folder+ layerfolder.py+pygimplib file here:
![image](https://user-images.githubusercontent.com/32169391/30700300-326d09f6-9eb5-11e7-87f2-802d15518c07.png)

I do not get an export layer option when I open the file menu.

Can you please help me figure out what I am doing wrong?

Thank you!

**Comment by khalim19** [comment] 2018-02-02 17:29
@Mavikaya8 The name of the .py file should be "export_layers.py", not "exportlayers.py". Are you sure you extracted all files from the package? Judging from the size of the .py file, it's a file from a different plug-in.

**Comment by Bragante18** [comment] 2018-04-30 16:43
Hy,

I am following the instructions, i've dowloaded the file (registered in the "C:programmes/software/Gimp 2"):
![image](https://user-images.githubusercontent.com/37066808/39438978-481a8bbc-4ca6-11e8-9add-ed813d787568.png)

Then, i copied the two files ("export_layers" and "export_layers.py") and pasted it in the "users"(me) inside the plug-in folder, as instructed:
![image](https://user-images.githubusercontent.com/37066808/39438918-15087068-4ca6-11e8-8155-546c9213bbb5.png)

 But it doesn't work, i do not have the new export options. I am learning web developpement and i can't afford Photoshop. I have to present a project working with a template and i really need to export the layers. Could anyone please help !

**Comment by khalim19** [comment] 2018-04-30 16:50
@Bragante18 Looks like you downloaded version 2.4, which very likely won't work for GIMP 2.10. Download the [latest version](https://github.com/khalim19/gimp-plugin-export-layers/releases) instead.

**Comment by Bragante18** [comment] 2018-04-30 16:59
Khalim19 you're just great ! Running perfectly !
Thank you very much for your support and for develop this plug-in !!

**Comment by khalim19** [comment] 2018-06-11 19:17
Closing this as no news was provided to the original issue.

**Closed by khalim19** 2018-06-11 19:17 UTC
